# Generated by Django 3.2.7 on 2021-09-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210929_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
