# Generated by Django 3.2.7 on 2021-09-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_pricelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'ordering': ['title'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
