# Generated by Django 3.2.7 on 2021-09-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pricecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'ordering': ['name'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='pricecategory',
            old_name='title',
            new_name='name',
        ),
    ]
