# Generated by Django 3.2.7 on 2021-09-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210929_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория'),
        ),
    ]
