# Generated by Django 3.2.7 on 2021-09-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pricecategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
    ]
