# Generated by Django 3.2.7 on 2021-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_worklist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Фото'),
        ),
    ]
