# Generated by Django 3.2.7 on 2021-10-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_worklist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecategory',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена'),
        ),
    ]
